In [1]:
import pandas as pd

questionarios = pd.read_csv('questoes.csv')

dados_dos_questionarios_filtrados = questionarios[['nome','questionario','Created Date', 'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10']]

primeiro_questionario = dados_dos_questionarios_filtrados[dados_dos_questionarios_filtrados['questionario'] == '["1"]']
segundo_questionario = dados_dos_questionarios_filtrados[dados_dos_questionarios_filtrados['questionario'] == '["2"]']
terceiro_questionario = dados_dos_questionarios_filtrados[dados_dos_questionarios_filtrados['questionario'] == '["3"]']

# QUESTIONARIO UM

In [2]:
primeiro_questionario.head(5)

,nome,questionario,Created Date,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10
6,talita da silva veras,"[""1""]",2023-08-18T10:51:43Z,B,A,D,B,B,A,D,D,A,C
8,Jéssica Meneses de Lima,"[""1""]",2023-08-18T10:39:00Z,D,A,D,C,B,B,C,C,B,B
9,Gabriel da Silva Laurindo,"[""1""]",2023-08-18T10:53:43Z,D,A,D,C,B,B,A,C,A,C
12,Ana Beatriz Duarte Silva,"[""1""]",2023-08-18T10:49:30Z,D,A,B,B,B,C,C,C,C,C
14,emilly tayna,"[""1""]",2023-08-18T10:59:03Z,D,A,D,B,B,B,A,A,D,D

## GABARITO
    
    1 – D
    2 – A
    3 – D
    4 – B
    5 – B
    6 – B
    7 – D
    8 – A
    9 – B
    10 – B

In [3]:
primeiro_questionario_copy = primeiro_questionario.copy()

primeiro_questionario_copy.loc[primeiro_questionario_copy['r1'] == 'D', 'r1'] = 'ACERTO'
primeiro_questionario_copy.loc[primeiro_questionario_copy['r2'] == 'A', 'r2'] = 'ACERTO'
primeiro_questionario_copy.loc[primeiro_questionario_copy['r3'] == 'D', 'r3'] = 'ACERTO'
primeiro_questionario_copy.loc[primeiro_questionario_copy['r4'] == 'B', 'r4'] = 'ACERTO'
primeiro_questionario_copy.loc[primeiro_questionario_copy['r5'] == 'B', 'r5'] = 'ACERTO'
primeiro_questionario_copy.loc[primeiro_questionario_copy['r6'] == 'B', 'r6'] = 'ACERTO'
primeiro_questionario_copy.loc[primeiro_questionario_copy['r7'] == 'D', 'r7'] = 'ACERTO'
primeiro_questionario_copy.loc[primeiro_questionario_copy['r8'] == 'A', 'r8'] = 'ACERTO'
primeiro_questionario_copy.loc[primeiro_questionario_copy['r9'] == 'B', 'r9'] = 'ACERTO'
primeiro_questionario_copy.loc[primeiro_questionario_copy['r10'] == 'B', 'r10'] = 'ACERTO'

#correção = segundo_questionario.mask(segundo_questionario == 'C', 'ACERTO')

primeiro_questionario_copy

,nome,questionario,Created Date,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10
6,talita da silva veras,"[""1""]",2023-08-18T10:51:43Z,B,ACERTO,ACERTO,ACERTO,ACERTO,A,ACERTO,D,A,C
8,Jéssica Meneses de Lima,"[""1""]",2023-08-18T10:39:00Z,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO,C,C,ACERTO,ACERTO
9,Gabriel da Silva Laurindo,"[""1""]",2023-08-18T10:53:43Z,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO,A,C,A,C
12,Ana Beatriz Duarte Silva,"[""1""]",2023-08-18T10:49:30Z,ACERTO,ACERTO,B,ACERTO,ACERTO,C,C,C,C,C
14,emilly tayna,"[""1""]",2023-08-18T10:59:03Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,A,ACERTO,D,D
25,Maico Antony Gouveia de Oliveira,"[""1""]",2023-08-18T10:38:27Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,C,ACERTO,ACERTO
27,Thaís de Oliveira Alves,"[""1""]",2023-08-18T10:41:31Z,ACERTO,ACERTO,ACERTO,C,C,ACERTO,ACERTO,ACERTO,ACERTO,C
28,jose rian ribeiro da silva,"[""1""]",2023-08-18T11:05:47Z,B,ACERTO,B,A,ACERTO,ACERTO,ACERTO,D,ACERTO,ACERTO
33,José Gustavo Maia Sabino,"[""1""]",2023-08-18T10:51:37Z,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO,C,ACERTO,ACERTO,D
34,Grazielle Braz de Oliveira,"[""1""]",2023-08-18T11:03:18Z,ACERTO,ACERTO,ACERTO,D,ACERTO,ACERTO,C,C,ACERTO,ACERTO
35,José Yan Ferreira Leite,"[""1""]",2023-08-18T10:45:22Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,C,ACERTO,ACERTO
36,Lívia Samily Delfino Carneiro,"[""1""]",2023-08-18T10:48:47Z,ACERTO,ACERTO,B,ACERTO,ACERTO,C,C,C,C,D
38,Bruna,"[""1""]",2023-08-18T11:07:02Z,ACERTO,ACERTO,B,C,ACERTO,ACERTO,NaN,C,A,C
40,kaique barros de lima,"[""1""]",2023-08-18T10:54:50Z,C,ACERTO,B,D,ACERTO,ACERTO,B,B,C,D
42,Plínio Manoel Cordeiro Rodrigues,"[""1""]",2023-08-18T10:51:50Z,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO,C,D,ACERTO,ACERTO
44,Marcos Antônio Pereira Nunes Florentino,"[""1""]",2023-08-18T10:54:22Z,ACERTO,ACERTO,B,C,ACERTO,ACERTO,C,D,ACERTO,ACERTO
46,Maria Clara,"[""1""]",2023-08-18T10:58:56Z,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO,C,ACERTO,C,D
49,Micaias Lopes Oliveira,"[""1""]",2023-08-18T10:37:39Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO

In [4]:
acertos_questionario1_questao1 = primeiro_questionario_copy['r1'].value_counts()['ACERTO']
acertos_questionario1_questao2 = primeiro_questionario_copy['r2'].value_counts()['ACERTO']
acertos_questionario1_questao3 = primeiro_questionario_copy['r3'].value_counts()['ACERTO']
acertos_questionario1_questao4 = primeiro_questionario_copy['r4'].value_counts()['ACERTO']
acertos_questionario1_questao5 = primeiro_questionario_copy['r5'].value_counts()['ACERTO']
acertos_questionario1_questao6 = primeiro_questionario_copy['r6'].value_counts()['ACERTO']
acertos_questionario1_questao7 = primeiro_questionario_copy['r7'].value_counts()['ACERTO']
acertos_questionario1_questao8 = primeiro_questionario_copy['r8'].value_counts()['ACERTO']
acertos_questionario1_questao9 = primeiro_questionario_copy['r9'].value_counts()['ACERTO']
acertos_questionario1_questao10 = primeiro_questionario_copy['r10'].value_counts()['ACERTO']

In [5]:
print(f'''ACERTOS:

questão 1:{acertos_questionario1_questao1}
questão 2: {acertos_questionario1_questao2} 
questão 3: {acertos_questionario1_questao3} 
questão 4: {acertos_questionario1_questao4} 
questão 5: {acertos_questionario1_questao5} 
questão 6: {acertos_questionario1_questao6}
questão 7: {acertos_questionario1_questao7}
questão 8: {acertos_questionario1_questao8}
questão 9: {acertos_questionario1_questao9}
questão 10: {acertos_questionario1_questao10}
   ''')

ACERTOS:

questão 1:15
questão 2: 18
questão 3: 12
questão 4: 7
questão 5: 17
questão 6: 15
questão 7: 4
questão 8: 5
questão 9: 10
questão 10: 8

In [6]:
primeiro_questionario_copy

,nome,questionario,Created Date,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10
6,talita da silva veras,"[""1""]",2023-08-18T10:51:43Z,B,ACERTO,ACERTO,ACERTO,ACERTO,A,ACERTO,D,A,C
8,Jéssica Meneses de Lima,"[""1""]",2023-08-18T10:39:00Z,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO,C,C,ACERTO,ACERTO
9,Gabriel da Silva Laurindo,"[""1""]",2023-08-18T10:53:43Z,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO,A,C,A,C
12,Ana Beatriz Duarte Silva,"[""1""]",2023-08-18T10:49:30Z,ACERTO,ACERTO,B,ACERTO,ACERTO,C,C,C,C,C
14,emilly tayna,"[""1""]",2023-08-18T10:59:03Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,A,ACERTO,D,D
25,Maico Antony Gouveia de Oliveira,"[""1""]",2023-08-18T10:38:27Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,C,ACERTO,ACERTO
27,Thaís de Oliveira Alves,"[""1""]",2023-08-18T10:41:31Z,ACERTO,ACERTO,ACERTO,C,C,ACERTO,ACERTO,ACERTO,ACERTO,C
28,jose rian ribeiro da silva,"[""1""]",2023-08-18T11:05:47Z,B,ACERTO,B,A,ACERTO,ACERTO,ACERTO,D,ACERTO,ACERTO
33,José Gustavo Maia Sabino,"[""1""]",2023-08-18T10:51:37Z,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO,C,ACERTO,ACERTO,D
34,Grazielle Braz de Oliveira,"[""1""]",2023-08-18T11:03:18Z,ACERTO,ACERTO,ACERTO,D,ACERTO,ACERTO,C,C,ACERTO,ACERTO
35,José Yan Ferreira Leite,"[""1""]",2023-08-18T10:45:22Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,C,ACERTO,ACERTO
36,Lívia Samily Delfino Carneiro,"[""1""]",2023-08-18T10:48:47Z,ACERTO,ACERTO,B,ACERTO,ACERTO,C,C,C,C,D
38,Bruna,"[""1""]",2023-08-18T11:07:02Z,ACERTO,ACERTO,B,C,ACERTO,ACERTO,NaN,C,A,C
40,kaique barros de lima,"[""1""]",2023-08-18T10:54:50Z,C,ACERTO,B,D,ACERTO,ACERTO,B,B,C,D
42,Plínio Manoel Cordeiro Rodrigues,"[""1""]",2023-08-18T10:51:50Z,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO,C,D,ACERTO,ACERTO
44,Marcos Antônio Pereira Nunes Florentino,"[""1""]",2023-08-18T10:54:22Z,ACERTO,ACERTO,B,C,ACERTO,ACERTO,C,D,ACERTO,ACERTO
46,Maria Clara,"[""1""]",2023-08-18T10:58:56Z,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO,C,ACERTO,C,D
49,Micaias Lopes Oliveira,"[""1""]",2023-08-18T10:37:39Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO

# QUESTIONARIO DOIS

In [7]:
segundo_questionario.head(5)

,nome,questionario,Created Date,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10
0,Maico Antony Gouveia de Oliveira,"[""2""]",2023-08-25T11:27:08Z,C,A,B,B,C,A,B,A,B,B
1,Grazielle Braz de Oliveira,"[""2""]",2023-08-25T11:29:46Z,B,A,B,B,C,A,B,C,C,C
4,Plínio Manoel Cordeiro Rodrigues,"[""2""]",2023-08-25T11:25:20Z,C,A,B,NaN,B,A,B,C,B,B
5,Micaias Lopes Oliveira,"[""2""]",2023-08-25T11:15:16Z,C,A,B,B,C,A,B,A,A,B
7,kaique barros,"[""2""]",2023-08-25T11:15:33Z,D,A,A,NaN,A,A,D,C,A,C

## GABARITO
    2º Questionário

    1 – C
    2 – A
    3 – B
    4 – B
    5 – C
    6 – A
    7 – B
    8 – A
    9 – B
    10 – B

In [8]:
segundo_questionario_copy = segundo_questionario.copy()

segundo_questionario_copy.loc[segundo_questionario_copy['r1'] == 'C', 'r1'] = 'ACERTO'
segundo_questionario_copy.loc[segundo_questionario_copy['r2'] == 'A', 'r2'] = 'ACERTO'
segundo_questionario_copy.loc[segundo_questionario_copy['r3'] == 'B', 'r3'] = 'ACERTO'
segundo_questionario_copy.loc[segundo_questionario_copy['r4'] == 'B', 'r4'] = 'ACERTO'
segundo_questionario_copy.loc[segundo_questionario_copy['r5'] == 'C', 'r5'] = 'ACERTO'
segundo_questionario_copy.loc[segundo_questionario_copy['r6'] == 'A', 'r6'] = 'ACERTO'
segundo_questionario_copy.loc[segundo_questionario_copy['r7'] == 'B', 'r7'] = 'ACERTO'
segundo_questionario_copy.loc[segundo_questionario_copy['r8'] == 'A', 'r8'] = 'ACERTO'
segundo_questionario_copy.loc[segundo_questionario_copy['r9'] == 'B', 'r9'] = 'ACERTO'
segundo_questionario_copy.loc[segundo_questionario_copy['r10'] == 'B', 'r10'] = 'ACERTO'

#correção = segundo_questionario.mask(segundo_questionario == 'C', 'ACERTO')

segundo_questionario_copy

,nome,questionario,Created Date,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10
0,Maico Antony Gouveia de Oliveira,"[""2""]",2023-08-25T11:27:08Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO
1,Grazielle Braz de Oliveira,"[""2""]",2023-08-25T11:29:46Z,B,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,C,C
4,Plínio Manoel Cordeiro Rodrigues,"[""2""]",2023-08-25T11:25:20Z,ACERTO,ACERTO,ACERTO,NaN,B,ACERTO,ACERTO,C,ACERTO,ACERTO
5,Micaias Lopes Oliveira,"[""2""]",2023-08-25T11:15:16Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,A,ACERTO
7,kaique barros,"[""2""]",2023-08-25T11:15:33Z,D,ACERTO,A,NaN,A,ACERTO,D,C,A,C
10,Lívia Samily Delfino Carneiro,"[""2""]",2023-08-25T11:24:48Z,D,D,ACERTO,ACERTO,B,ACERTO,ACERTO,C,ACERTO,C
13,Marcos Antonio Pereira Nunes Florentino,"[""2""]",2023-08-25T11:22:25Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,D,ACERTO,C
15,JOSE RIAN,"[""2""]",2023-08-25T11:26:37Z,ACERTO,ACERTO,C,ACERTO,ACERTO,ACERTO,C,D,ACERTO,C
16,talita da silva veras,"[""2""]",2023-08-25T11:20:26Z,D,D,ACERTO,ACERTO,ACERTO,B,ACERTO,C,ACERTO,D
18,giovanna thavinny ramos batista,"[""2""]",2023-08-25T11:23:23Z,ACERTO,ACERTO,ACERTO,A,ACERTO,ACERTO,ACERTO,C,C,D
19,Maria Clara Alves Frazão,"[""2""]",2023-08-25T11:21:43Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,D,C,ACERTO,C
20,Bruna Gomes Vieira da Silva,"[""2""]",2023-08-25T11:23:38Z,ACERTO,ACERTO,ACERTO,A,ACERTO,ACERTO,ACERTO,C,C,C
21,emilly tayna silverio,"[""2""]",2023-08-25T11:22:48Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,C,D
22,guilherme alves,"[""2""]",2023-08-25T11:23:46Z,A,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,D,D,C
23,Daniel,"[""2""]",2023-08-25T11:23:01Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,D,ACERTO,C
26,alysson bezerra,"[""2""]",2023-08-25T11:22:09Z,B,D,D,C,D,ACERTO,D,B,D,A
30,Jéssica Meneses de Lima,"[""2""]",2023-08-25T11:20:36Z,ACERTO,ACERTO,ACERTO,ACERTO,B,ACERTO,ACERTO,C,D,C
31,Thaís de Oliveira Alves,"[""2""]",2023-08-25T11:34:45Z,ACERTO,C,ACERTO,A,B,ACERTO,C,C,ACERTO,ACERTO
32,Ruanderson Silva Sousa,"[""2""]",2023-08-25T11:22:53Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,A,D
39,Erick Guilherme Nascimento da silva,"[""2""]",2023-08-25T11:40:49Z,ACERTO,C,A,C,B,D,A,C,D,C
43,José Gustavo Maia Sabino,"[""2""]",2023-08-25T11:23:40Z,ACERTO,ACERTO,D,A,ACERTO,ACERTO,D,ACERTO,ACERTO,ACERTO
45,Gabriel da Silva Laurindo,"[""2""]",2023-08-25T11:18:58Z,ACERTO,ACERTO,D,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,D
47,Ana Beatriz Duarte Silva,"[""2""]",2023-08-25T11:24:55Z,D,D,ACERTO,ACERTO,B,ACERTO,ACERTO,C,ACERTO,C
48,José Yan Ferreira Leite,"[""2""]",2023-08-25T11:18:27Z,ACERTO,C,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO

In [9]:
'''
acertos_questao1 = segundo_questionario_copy.groupby(['r2']).size()
acertos_questao2 = segundo_questionario_copy.groupby(['r2']).size()
acertos_questao3 = segundo_questionario_copy.groupby(['r3']).size()
acertos_questao4 = segundo_questionario_copy.groupby(['r4']).size()
acertos_questao5 = segundo_questionario_copy.groupby(['r5']).size()
acertos_questao6 = segundo_questionario_copy.groupby(['r6']).size()
acertos_questao7 = segundo_questionario_copy.groupby(['r7']).size()
acertos_questao8 = segundo_questionario_copy.groupby(['r8']).size()
acertos_questao9 = segundo_questionario_copy.groupby(['r9']).size()
acertos_questao10 = segundo_questionario_copy.groupby(['r10']).size()
'''

acertos_questao1 = segundo_questionario_copy['r1'].value_counts()['ACERTO']
acertos_questao2 = segundo_questionario_copy['r2'].value_counts()['ACERTO']
acertos_questao3 = segundo_questionario_copy['r3'].value_counts()['ACERTO']
acertos_questao4 = segundo_questionario_copy['r4'].value_counts()['ACERTO']
acertos_questao5 = segundo_questionario_copy['r5'].value_counts()['ACERTO']
acertos_questao6 = segundo_questionario_copy['r6'].value_counts()['ACERTO']
acertos_questao7 = segundo_questionario_copy['r7'].value_counts()['ACERTO']
acertos_questao8 = segundo_questionario_copy['r8'].value_counts()['ACERTO']
acertos_questao9 = segundo_questionario_copy['r9'].value_counts()['ACERTO']
acertos_questao10 = segundo_questionario_copy['r10'].value_counts()['ACERTO']

In [10]:
print(f'''ACERTOS:

questão 1:{acertos_questao1}
questão 2: {acertos_questao2} 
questão 3: {acertos_questao3} 
questão 4: {acertos_questao4} 
questão 5: {acertos_questao5} 
questão 6: {acertos_questao6}
questão 7: {acertos_questao7}
questão 8: {acertos_questao8}
questão 9: {acertos_questao9}
questão 10: {acertos_questao10}
   ''')

ACERTOS:

questão 1:17
questão 2: 17
questão 3: 18
questão 4: 16
questão 5: 16
questão 6: 22
questão 7: 17
questão 8: 4
questão 9: 12
questão 10: 6

In [11]:
segundo_questionario_copy.describe()

,nome,questionario,Created Date,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10
count,24,24,24,24,24,24,22,24,24,24,24,24,24
unique,24,1,24,4,3,4,3,4,3,4,4,4,4
top,Maico Antony Gouveia de Oliveira,"[""2""]",2023-08-25T11:27:08Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,ACERTO,C
freq,1,24,1,17,17,18,16,16,22,17,15,12,12

# QUESTIONARIO 3

In [12]:
terceiro_questionario

,nome,questionario,Created Date,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10
2,"Lívia Samily Delfino, Bruna Gomes Viera, Maria...","[""3""]",2023-08-25T12:19:01Z,C,A,A,B,C,A,D,C,B,C
3,Talita da Silva Veras; Micaias Oliveira; Erick...,"[""3""]",2023-08-25T12:18:55Z,C,A,A,B,C,A,B,A,A,B
11,NaN,"[""3""]",2023-08-25T12:15:42Z,B,A,C,C,C,A,D,A,A,D
17,"Maico Antony, Jéssica Meneses, Thaís de Oliveira","[""3""]",2023-08-25T12:18:25Z,C,A,A,B,C,A,B,A,B,B
24,"Marcos Antonio Pereira Nunes Florentino, Jose ...","[""3""]",2023-08-25T12:15:07Z,C,A,A,B,C,A,B,D,B,C
29,"José Yan, Plínio Manoel, José Gustavo.","[""3""]",2023-08-25T12:22:18Z,C,A,A,B,C,A,B,C,B,B
37,"Giovanna Thavinny, Ruanderson Silva Sousa, Emi...","[""3""]",2023-08-25T12:17:54Z,C,A,A,B,C,A,B,C,B,C
41,"Ana Beatriz, Grazielle Braz, Gabriel Laurindo","[""3""]",2023-08-25T12:19:46Z,C,A,A,B,C,A,B,A,C,C

## GABARITO

    3º Questionário

    1 – C
    2 – A
    3 – A
    4 – B
    5 – C
    6 – A
    7 – B
    8 – A
    9 – B
    10 – B

In [13]:
terceiro_questionario_copy = terceiro_questionario.copy()

terceiro_questionario_copy.loc[terceiro_questionario_copy['r1'] == 'C', 'r1'] = 'ACERTO'
terceiro_questionario_copy.loc[terceiro_questionario_copy['r2'] == 'A', 'r2'] = 'ACERTO'
terceiro_questionario_copy.loc[terceiro_questionario_copy['r3'] == 'A', 'r3'] = 'ACERTO'
terceiro_questionario_copy.loc[terceiro_questionario_copy['r4'] == 'B', 'r4'] = 'ACERTO'
terceiro_questionario_copy.loc[terceiro_questionario_copy['r5'] == 'C', 'r5'] = 'ACERTO'
terceiro_questionario_copy.loc[terceiro_questionario_copy['r6'] == 'A', 'r6'] = 'ACERTO'
terceiro_questionario_copy.loc[terceiro_questionario_copy['r7'] == 'B', 'r7'] = 'ACERTO'
terceiro_questionario_copy.loc[terceiro_questionario_copy['r8'] == 'A', 'r8'] = 'ACERTO'
terceiro_questionario_copy.loc[terceiro_questionario_copy['r9'] == 'B', 'r9'] = 'ACERTO'
terceiro_questionario_copy.loc[terceiro_questionario_copy['r10'] == 'B', 'r10'] = 'ACERTO'

terceiro_questionario_copy

,nome,questionario,Created Date,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10
2,"Lívia Samily Delfino, Bruna Gomes Viera, Maria...","[""3""]",2023-08-25T12:19:01Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,D,C,ACERTO,C
3,Talita da Silva Veras; Micaias Oliveira; Erick...,"[""3""]",2023-08-25T12:18:55Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,A,ACERTO
11,NaN,"[""3""]",2023-08-25T12:15:42Z,B,ACERTO,C,C,ACERTO,ACERTO,D,ACERTO,A,D
17,"Maico Antony, Jéssica Meneses, Thaís de Oliveira","[""3""]",2023-08-25T12:18:25Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO
24,"Marcos Antonio Pereira Nunes Florentino, Jose ...","[""3""]",2023-08-25T12:15:07Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,D,ACERTO,C
29,"José Yan, Plínio Manoel, José Gustavo.","[""3""]",2023-08-25T12:22:18Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,ACERTO,ACERTO
37,"Giovanna Thavinny, Ruanderson Silva Sousa, Emi...","[""3""]",2023-08-25T12:17:54Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,ACERTO,C
41,"Ana Beatriz, Grazielle Braz, Gabriel Laurindo","[""3""]",2023-08-25T12:19:46Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C,C

In [14]:
acertos_questionario3_questao1 = terceiro_questionario_copy['r1'].value_counts()['ACERTO']
acertos_questionario3_questao2 = terceiro_questionario_copy['r2'].value_counts()['ACERTO']
acertos_questionario3_questao3 = terceiro_questionario_copy['r3'].value_counts()['ACERTO']
acertos_questionario3_questao4 = terceiro_questionario_copy['r4'].value_counts()['ACERTO']
acertos_questionario3_questao5 = terceiro_questionario_copy['r5'].value_counts()['ACERTO']
acertos_questionario3_questao6 = terceiro_questionario_copy['r6'].value_counts()['ACERTO']
acertos_questionario3_questao7 = terceiro_questionario_copy['r7'].value_counts()['ACERTO']
acertos_questionario3_questao8 = terceiro_questionario_copy['r8'].value_counts()['ACERTO']
acertos_questionario3_questao9 = terceiro_questionario_copy['r9'].value_counts()['ACERTO']
acertos_questionario3_questao10 = terceiro_questionario_copy['r10'].value_counts()['ACERTO']

In [15]:
print(f'''ACERTOS:

questão 1:{acertos_questionario3_questao1}
questão 2: {acertos_questionario3_questao2} 
questão 3: {acertos_questionario3_questao3} 
questão 4: {acertos_questionario3_questao4} 
questão 5: {acertos_questionario3_questao5} 
questão 6: {acertos_questionario3_questao6}
questão 7: {acertos_questionario3_questao7}
questão 8: {acertos_questionario3_questao8}
questão 9: {acertos_questionario3_questao9}
questão 10: {acertos_questionario3_questao10}
   ''')

ACERTOS:

questão 1:7
questão 2: 8
questão 3: 7
questão 4: 7
questão 5: 8
questão 6: 8
questão 7: 6
questão 8: 4
questão 9: 5
questão 10: 3

In [16]:
terceiro_questionario_copy.describe()

,nome,questionario,Created Date,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10
count,7,8,8,8,8,8,8,8,8,8,8,8,8
unique,7,1,8,2,1,2,2,1,1,2,3,3,3
top,"Lívia Samily Delfino, Bruna Gomes Viera, Maria...","[""3""]",2023-08-25T12:19:01Z,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,ACERTO,C
freq,1,8,1,7,8,7,7,8,8,6,4,5,4